name: GH-Actions-postman-newman

on:
  push:
    branches: [ "main", "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
 test-run:
    # runs-on: ubuntu-latest
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - uses: actions/setup-node@v2
      with:
          node-version: '14.x'
    - name: Install dependencies
      run: npm i
    - name: Install Newman
      run: npm install -g newman
    - name: Install newman Allure rporter
      run: npm install -g newman-reporter-allure
    - name: Run API tests
      run: npm run petstore:allureReport
    - name: Generate Report
      if: always()
      run: npm run allure:generate
    - name: Upload Results
      uses: actions/upload-artifact@v1
      if: always()
      with:
          name: allure-results
          path: ./allure-results
    - name: Publishing Allure artifact to Github Actions
      uses: actions/upload-artifact@v2
      if: always()
      with:
          name: allure-report
          path: allure-report   
    - name: Deploy to pages
      if: always()
      uses: peaceiris/actions-gh-pages@v3.7.3
    
